# Used to integrate with Microsoft VS Code remote debug feature.
---
version: "3.8"
services:
  nautobot:
    ports:
      - "{{cookiecutter.nautobot_port}}:8080"
      - "{{cookiecutter.vscode_rdb_nautobot_port}}:6899"
    entrypoint: ""
    command: sh -c "
      pip install debugpy &&
      /docker-entrypoint.sh &&
      python -m debugpy --listen 0.0.0.0:6899 -m nautobot-server runserver 0.0.0.0:8080 --insecure"
  celery_worker:
    ports:
      - "{{cookiecutter.vscode_rdb_celery_port}}:6898"
    entrypoint: ""
    command: sh -c "
      pip install debugpy &&
      watchmedo auto-restart --directory './' --pattern '*.py' --recursive -- python -m debugpy --listen 0.0.0.0:6898 -m nautobot-server celery worker -l INFO --events"
